spring:
  main:
    allow-bean-definition-overriding: true
zuul:
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
