#解决前端问题：he ‘Access-Control-Allow-Origin’ header contains multiple values ‘, ‘, but only one is allowed.
zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin, Vary, X-Frame-Options
